---
title: "reporting"
author: "Patrick Ding"
date: "4/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("reporting_tools.R")
# library(clipr)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(scales)
```

## Blog Catalog

### LaTeX Tables

```{r}
load(file = "perf_data/blog.Rda")

bg_perf_t1_micro <- perf_table(bg_perf$micro_f1, TRUE, table_format = "latex", 
                               font_size = 10, 
                               title = "Blog Catalog, Type I, F1-Micro")
bg_perf_t1_macro <- perf_table(bg_perf$macro_f1, TRUE, table_format = "latex", 
                               font_size = 10, 
                               title = "Blog Catalog, Type I, F1-Macro")
bg_perf_t2_micro <- perf_table(bg_perf$micro_f1, FALSE, table_format = "latex", 
                               font_size = 10, 
                               title = "Blog Catalog, Type II, F1-Micro")
bg_perf_t2_macro <- perf_table(bg_perf$macro_f1, FALSE, table_format = "latex", 
                               font_size = 10, 
                               title = "Blog Catalog, Type II, F1-Macro")

write_clip(bg_perf_t1_micro)
write_clip(bg_perf_t1_macro)
write_clip(bg_perf_t2_micro)
write_clip(bg_perf_t2_macro)
```

### Plots

```{r}
bg_compare_dat <- 
  rbind(
    perf_as_df(rowMeans(bg_perf$micro_f1, FALSE, 2), "Micro-F1"),
    perf_as_df(rowMeans(bg_perf$macro_f1, FALSE, 2), "Macro-F1"),
    perf_as_df(apply(bg_perf$micro_f1, c(1, 2), function(x) sd(x) / sqrt(5)), "Micro-F1_sd"),
    perf_as_df(apply(bg_perf$macro_f1, c(1, 2), function(x) sd(x) / sqrt(5)), "Macro-F1_sd")
  ) %>% 
  # filter(Method %in% c("kkk_BlogCatalog", "LINE_BlogCatalog", 
                       # "nopenalty_BlogCatalog", "rns_015_BlogCatalog")) %>%
  gather(key = "Split", value = "Score", -Method, -Type, -measure) %>%
  mutate(Labeled = as.numeric(str_replace(Split, "split_", "")),
         Data = "Blog Catalog",
         Penalty = str_extract(Method, "\\d{2,4}") %>% 
           paste0(".", .) %>% 
           as.numeric(),
         Method = str_replace(Method, "_.*", ""))

# bg_compare_dat %>% 
#   filter(measure == "Micro-F1" & Type == "t1_embed") %>%
#   ggplot(aes(x = Labeled, y = Score, color = Method)) +
#     geom_path() + geom_point() +
#     theme_minimal() + 
#     theme(legend.position = "bottom")

# cherry pick most favorable comparison between RNS, others
bg_rns_best <- bg_compare_dat %>%
  filter(Labeled == 0.5, Type == "t2_embed", measure == "Micro-F1",
         Method == "rns", Penalty == 0.0197)

bg_ns_best <- bg_compare_dat %>%
  filter(Labeled == 0.5, Type == "t2_embed", measure == "Micro-F1",
         Method == "LINE")

(bg_rns_best$Score / bg_ns_best$Score) - 1
```

## Wikipedia

### LaTeX Tables

```{r}
load(file = "perf_data/wiki.Rda")

wiki_perf_t1_micro <- perf_table(wiki_perf$micro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "Wikipedia, Type I, F1-Micro")
wiki_perf_t1_macro <- perf_table(wiki_perf$macro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "Wikipedia, Type I, F1-Macro")
wiki_perf_t2_micro <- perf_table(wiki_perf$micro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "Wikipedia, Type II, F1-Micro")
wiki_perf_t2_macro <- perf_table(wiki_perf$macro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "Wikipedia, Type II, F1-Macro")

write_clip(wiki_perf_t1_micro)
write_clip(wiki_perf_t1_macro)
write_clip(wiki_perf_t2_micro)
write_clip(wiki_perf_t2_macro)
```

### Plots

```{r}
wiki_compare_dat <- 
  rbind(
    perf_as_df(rowMeans(wiki_perf$micro_f1, FALSE, 2), "Micro-F1"),
    perf_as_df(rowMeans(wiki_perf$macro_f1, FALSE, 2), "Macro-F1")
  ) %>% 
  # filter(Method %in% c("kkk_POS", "LINE_POS", 
  #                      "nopenalty_POS", "rns_02_POS")) %>%
  gather(key = "Split", value = "Score", -Method, -Type, -measure) %>%
  mutate(Labeled = as.numeric(str_replace(Split, "split_", "")),
         Data = "Wikipedia",
         Penalty = str_extract(Method, "\\d{2,4}") %>% 
           paste0(".", .) %>% 
           as.numeric(),
         Method = str_replace(Method, "_.*", ""))
```

## PPI

### LaTeX Tables

```{r}
load(file = "perf_data/ppi.Rda")

ppi_perf_t1_micro <- perf_table(ppi_perf$micro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "PPI, Type I, F1-Micro")
ppi_perf_t1_macro <- perf_table(ppi_perf$macro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "PPI, Type I, F1-Macro")
ppi_perf_t2_micro <- perf_table(ppi_perf$micro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "PPI, Type II, F1-Micro")
ppi_perf_t2_macro <- perf_table(ppi_perf$macro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "PPI, Type II, F1-Macro")

write_clip(ppi_perf_t1_micro)
write_clip(ppi_perf_t1_macro)
write_clip(ppi_perf_t2_micro)
write_clip(ppi_perf_t2_macro)
```

### Plots

```{r}
ppi_compare_dat <- 
  rbind(
    perf_as_df(rowMeans(ppi_perf$micro_f1, FALSE, 2), "Micro-F1"),
    perf_as_df(rowMeans(ppi_perf$macro_f1, FALSE, 2), "Macro-F1")
  ) %>% 
  # filter(Method %in% c("kkk_ppi", "LINE_ppi", 
  #                      "nopenalty_ppi", "rns_015_ppi")) %>%
  gather(key = "Split", value = "Score", -Method, -Type, -measure) %>%
  mutate(Labeled = as.numeric(str_replace(Split, "split_", "")),
         Data = "PPI (Homo Sapiens)",
         Penalty = str_extract(Method, "\\d{2,4}") %>% 
           paste0(".", .) %>% 
           as.numeric(),
         Method = str_replace(Method, "_.*", ""))
```

## Flickr

### LaTeX Tables

```{r}
load(file = "perf_data/flickr.Rda")

flickr_perf_t1_micro <- perf_table(flickr_perf$micro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "flickr, Type I, F1-Micro")
flickr_perf_t1_macro <- perf_table(flickr_perf$macro_f1, TRUE, table_format = "latex", font_size = 10, 
                               title = "flickr, Type I, F1-Macro")
flickr_perf_t2_micro <- perf_table(flickr_perf$micro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "flickr, Type II, F1-Micro")
flickr_perf_t2_macro <- perf_table(flickr_perf$macro_f1, FALSE, table_format = "latex", font_size = 10, 
                               title = "flickr, Type II, F1-Macro")

write_clip(flickr_perf_t1_micro)
write_clip(flickr_perf_t1_macro)
write_clip(flickr_perf_t2_micro)
write_clip(flickr_perf_t2_macro)
```

```{r}
flickr_compare_dat <- 
  rbind(
    perf_as_df(rowMeans(flickr_perf$micro_f1, FALSE, 2), "Micro-F1"),
    perf_as_df(rowMeans(flickr_perf$macro_f1, FALSE, 2), "Macro-F1")
  ) %>% 
  # filter(Method %in% c("kkk_flickr", "true_line_flickr", 
  #                      "nopenalty_flickr", "rns_008_flickr")) %>%
  gather(key = "Split", value = "Score", -Method, -Type, -measure) %>%
  mutate(Labeled = as.numeric(str_replace(Split, "split_", "")),
         Data = "Flickr",
         Penalty = str_extract(Method, "\\d{2,4}") %>%
           paste0(".", .) %>% 
           as.numeric(),
         Method = str_replace_all(Method, "_flickr|_\\d{2,4}|true_", "") %>%
                  str_replace("line", "LINE"))

flickr_rns_best <- flickr_compare_dat %>%
  filter(Labeled == 0.1, Type == "t2_embed", measure == "Micro-F1",
         Method == "rns", Penalty == 0.0186)

flickr_ns_best <- flickr_compare_dat %>%
  filter(Labeled == 0.1, Type == "t2_embed", measure == "Micro-F1",
         Method == "LINE") 

(flickr_rns_best$Score / flickr_ns_best$Score) - 1
```

## Combined Performance Plot

```{r}
compare_dat <- rbind(flickr_compare_dat, bg_compare_dat, #ppi_compare_dat, 
                     wiki_compare_dat) %>%
  mutate(Method = str_replace_all(Method, 
                                  c("kkk" = "NN-NS", 
                                    "LINE" = "NS",
                                    "rns" = "RNS",
                                    "nopenalty" = "RNS No Penalty")))

comp_dat <- compare_dat %>%
  filter(Method %in% c("NS", "RNS No Penalty", "NN-NS") | 
           Type == "t1_embed" & Penalty %in% c(0.0154, 0.0144, 0.0178) |
           Type == "t2_embed" & Penalty %in% c(0.0197, 0.0186, 0.0224)
  )
  
comp_I_micro_plot <- comp_dat %>%
  filter(measure == "Micro-F1", Type == "t1_embed") %>%
  ggplot(aes(x = Labeled, y = Score, color = Method)) +
    facet_wrap(~ Data, scales = "free", nrow = 1) +
    geom_path() + geom_point(aes(shape = Method)) +
    theme_bw() + 
    theme(legend.position = "bottom", legend.text = element_text(size = 12),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    scale_x_continuous(breaks = seq(0, 1, 0.2))
comp_I_macro_plot <- comp_I_micro_plot %+% 
  filter(comp_dat, measure == "Macro-F1", Type == "t1_embed")
  
comp_II_micro_plot <- (comp_I_micro_plot + ggtitle("Type II Objective")) %+% 
  filter(comp_dat, measure == "Micro-F1", Type == "t2_embed")
comp_II_macro_plot <- (comp_II_micro_plot) %+% 
  filter(comp_dat, measure == "Macro-F1", Type == "t2_embed")

comp_plot <- plot_grid(
  ggdraw() + draw_label("Type I Objective", x = 0, hjust = 0),
  ggdraw() + draw_label("Type II Objective", x = 0, hjust = 0),
  comp_I_micro_plot + labs(title = "Micro-F1") + theme(legend.position = "none"), 
  comp_II_micro_plot + labs(title = "Micro-F1") + theme(legend.position = "none"), 
  comp_I_macro_plot + labs(title = "Macro-F1") + theme(legend.position = "none"),
  comp_II_macro_plot + labs(title = "Macro-F1") + theme(legend.position = "none"),
  nrow = 3, ncol = 2, rel_heights = c(.1, 1, 1), rel_widths = c(1, 1)
) %>% plot_grid(get_legend(comp_I_micro_plot), ncol = 1, rel_heights = c(1, .1))

ggsave("comp.pdf", plot = comp_plot, device = "pdf", path = "plots", 
       height = 5, width = 11)
```

## Tuning Plot

```{r}
tune_dat <- compare_dat %>% 
  filter(Method %in% c("NS", "RNS"), Labeled == 0.5) %>%
  group_by(Data, measure, Type) %>%
  mutate(NS_Score = Score[Method == "NS"],
         Penalty = Penalty * 3) 
  
tune_I_micro_plot <- tune_dat %>%
  filter(measure == "Micro-F1", Type == "t1_embed") %>%
  ggplot(aes(x = Penalty, y = Score)) +
    facet_wrap(~ Data, scales = "free", nrow = 1) +
    geom_path() + geom_point() + 
    geom_line(aes(x = Penalty, y = NS_Score), color = "red") +
    theme_bw() +
    theme(legend.position = "bottom", legend.text = element_text(size = 12),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
tune_I_macro_plot <- tune_I_micro_plot %+% 
  filter(tune_dat, measure == "Macro-F1", Type == "t1_embed")

tune_II_micro_plot <- tune_I_micro_plot %+% 
  filter(tune_dat, measure == "Micro-F1", Type == "t2_embed")
tune_II_macro_plot <- tune_I_macro_plot %+%
  filter(tune_dat, measure == "Macro-F1", Type == "t2_embed")
  
tune_plot <- plot_grid(
  ggdraw() + draw_label("Type I Objective", x = 0, hjust = 0),
  ggdraw() + draw_label("Type II Objective", x = 0, hjust = 0),
  tune_I_micro_plot + labs(title = "Micro-F1") + theme(legend.position = "none"),  
  tune_II_micro_plot + labs(title = "Micro-F1") + theme(legend.position = "none"),  
  tune_I_macro_plot + labs(title = "Macro-F1") + theme(legend.position = "none"), 
  tune_II_macro_plot + labs(title = "Macro-F1") + theme(legend.position = "none"), 
  nrow = 3, rel_heights = c(.1, 1, 1), rel_widths = c(1, 1)
)

ggsave("tune.pdf", plot = tune_plot, device = "pdf", path = "plots", 
       height = 5, width = 11)
```

## node2vec style gain table

## 3d score plot

```{r}
# Color coding
flickr_compare_dat %>%
  filter(Type == "t2_embed", measure == "Micro-F1") %>%
  filter(Penalty %in% c(0.0186, NA)) %>%
  mutate(Penalty = as.factor(Penalty),
         PMethod = paste0(Method, Penalty)) %>%
  ggplot(aes(x = Labeled, y = Score, color = PMethod)) +
    geom_point() + geom_path() + 
    # geom_text_repel(data = filter(wiki_compare_dat, 
    #                       Method == "rns", Type == "t1_embed", 
    #                       measure == "Micro-F1", Labeled == 0.9) %>%
    #                   mutate(Penalty = as.factor(Penalty)),
    #                 aes(label = Penalty), nudge_x = 20,
    #                 point.padding = unit(0.02, 'npc'),
    #                 arrow = arrow(length = unit(0.02, 'npc'))) +
    theme_bw() + 
    # theme(legend.position = "none", legend.text = element_blank()) +
    scale_x_continuous(breaks = seq(0, 1, 0.2)) +
    coord_cartesian(xlim = c(0.05, 1)) 
    

# Penalty Panels 
wiki_compare_dat %>%
  filter(Method == "rns", Type == "t1_embed", measure == "Micro-F1") %>%
  mutate(Penalty = as.factor(Penalty)) %>%
  ggplot(aes(x = Labeled, y = Score)) +
    facet_grid(~ Penalty) +
    geom_point() + geom_path() +
    scale_x_continuous(breaks = seq(0, 1, 0.2)) +
    labs(title = "Wikipedia, Type I Embedding, Penalty Effect")
```

## Combined Table

```{r micro/macro f1 table data}
compare_table <- compare_dat %>% 
  group_by(Method, Type, measure, Labeled, Data) %>%
  # mutate(is_best = Score == max(Score)) %>%
  mutate(is_best = ifelse(Method == "RNS",
                          (Type == "t1_embed" & Penalty %in% 
                             c(0.0154, 0.0144, 0.0178)) |
                            (Type == "t2_embed" & Penalty %in% 
                               c(0.0197, 0.0186, 0.0224)), 
                          Score == max(Score))) %>%
  ungroup() %>%
  filter(Labeled == 0.5 & is_best)
  
# Type I embedding
compare_table %>% 
  filter(Type == "t1_embed", measure == "Micro-F1") %>%
  select(-Type, -Split, -Labeled, -is_best) %>%
  unite(m_data, measure, Data) %>%
  spread(key = m_data, value = Score)

compare_table %>% 
  filter(Type == "t1_embed", measure == "Macro-F1") %>%
  select(-Type, -Split, -Labeled, -is_best) %>%
  unite(m_data, measure, Data) %>%
  spread(key = m_data, value = Score)

# Type II embedding
compare_table %>% 
  filter(Type == "t2_embed", measure == "Micro-F1") %>%
  select(-Type, -Split, -Labeled, -is_best) %>%
  spread(key = Data, value = Score)

compare_table %>% 
  filter(Type == "t2_embed", measure == "Macro-F1") %>%
  select(-Type, -Split, -Labeled, -is_best) %>%
  spread(key = Data, value = Score)
  
  unite(m_data, measure, Data) %>%
  spread(key = m_data, value = Score)

compare_dat %>% filter(Method == "rns", measure == "Macro-F1")
```

```{r uncertainty} 
compare_table %>% 
  filter(Type == "t2_embed", measure == "Micro-F1") %>% 
  group_by(Type, measure, Method) %>%
  mutate(sd = sd(Score)) %>% ungroup() %>%
  select(-Type, -Split, -Labeled, -is_best) %>%
  spread(key = Data, value = Score)
```
